#!/usr/bin/env bash
#displays Best School 10 times, but for the 9th iteration, displays
#Best School and then Hi on a new line
i=1
while [ $i -le 10 ]
do
	echo "Best School"
	if [ $i -eq 9 ]; then
	   echo "Hi"
	fi
	i=$((i+1))
done
